### ISSUE TITLE
error once someone will click the emoji

### ISSUE THREAD

**Issue by Tomz10105** [thirdweb-dev/support-discord-bot#13]
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [MessageExistingThread]: The message already has a thread
    at Message.startThread (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\discord.js\src\structures\Message.js:844:47)
    at Client.<anonymous> (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\src\bot.js:147:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'MessageExistingThread'
}

Node.js v18.15.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by warengonzaga** [comment]
That means the thread is already created with that particular message. Also, double-check if you are running two instances of the bot. Maybe you are running on one from the server and one on your local. Check that.

**Comment by Tomz10105** [comment]
i got new error 

node:internal/crypto/sig:131
  const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
                            ^

Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\jws\lib\sign-stream.js:32:24)
    at GoogleToken.requestToken (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\gtoken\build\src\index.js:225:31)
    at GoogleToken.getTokenAsyncInner (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\gtoken\build\src\index.js:163:21)      
    at GoogleToken.getTokenAsync (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\gtoken\build\src\index.js:142:55)
    at GoogleToken.getToken (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\gtoken\build\src\index.js:94:21)
    at JWT.refreshTokenNoCache (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\google-auth-library\build\src\auth\jwtclient.js:158:36)
    at JWT.refreshToken (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\google-auth-library\build\src\auth\oauth2client.js:143:25)
    at JWT.authorizeAsync (C:\Users\Administrator\Desktop\thirdweb-support-discord-bot-main\node_modules\google-auth-library\build\src\auth\jwtclient.js:139:35) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}

**Comment by Tomz10105** [comment]
Already fixed this one <3

**Comment by warengonzaga** [comment]
Awesome, we can now close this issue @Tomz10105
