### ISSUE TITLE
forumPost.availableTags is not iterable

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/support-discord-bot#30]
## Error Log

```
node:events:491
throw er; // Unhandled 'error' event
^
TypeError: forumPost.availableTags is not iterable
at Client.<anonymous> (/app/src/bot.js:160:40)
at Client.emit (node:events:513:28)
at ThreadCreateAction.handle (/app/node_modules/discord.js/src/client/actions/ThreadCreate.js:18:14)
at module.exports [as THREAD_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/THREAD_CREATE.js:4:31)
at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
at callListener (/app/node_modules/ws/lib/event-target.js:290:14)
at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:209:9)
at WebSocket.emit (node:events:513:28)
Emitted 'error' event on Client instance at:
at emitUnhandledRejectionOrErr (node:events:394:10)
at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Node.js v18.12.1
error Command failed with exit code 1.
```

**Comment by warengonzaga** [comment]
No longer a bug as we remove the code related to this with v3 code.
